# Generated by Django 3.0.3 on 2020-02-09 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_entry_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subentry',
            name='subhead',
        ),
        migrations.CreateModel(
            name='SubHeadAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('sub_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.SubHead')),
            ],
        ),
        migrations.AddField(
            model_name='subentry',
            name='sub_head_account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account_app.SubHeadAccount'),
        ),
    ]
