# Generated by Django 3.0.3 on 2020-02-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_auto_20200209_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subheadaccount',
            old_name='title',
            new_name='sub_head_account',
        ),
        migrations.AddField(
            model_name='subentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
