# Generated by Django 3.0.3 on 2020-02-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_auto_20200210_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='account_app.SubEntry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='debit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit', to='account_app.SubEntry'),
        ),
    ]
