# Generated by Django 3.0.3 on 2020-02-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0010_auto_20200210_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subhead',
            name='sub_head',
            field=models.CharField(max_length=100),
        ),
    ]
