# Generated by Django 3.0.3 on 2020-02-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0011_auto_20200210_1547'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('debit', 'credit')},
        ),
    ]
