# Generated by Django 3.0.3 on 2020-02-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0012_auto_20200211_1409'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='entry',
            index_together={('debit', 'credit')},
        ),
    ]
